name: trekking_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0-91.0.dev


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kartal: ^4.1.0
  vexana: ^5.0.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  envied: ^0.5.4+1
  flutter_launcher_icons: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  very_good_analysis: ^6.0.0
  flutter_gen_runner: ^5.7.0



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter_gen:
  outputs: lib/product/generated
  integrations:
    lottie: true



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
